ERP/ERP/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('clinic.urls')),
]

ERP/clinic/urls.py
from django.conf.urls import url

from . import views

app_name = "clinic"

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),

    url(r'^CRM-DentalClinic-Overview',views.crm_dentalclinic_overview, name='CRM-DentalClinic-Overview'),
    url(r'^CRM-ContactCenter-Overview',views.crm_contactcenter_overview, name='CRM-ContactCenter-Overview'),
    url(r'^CRM-OpenChannel-Overview',views.crm_openchannel_overview, name='CRM-OpenChannel-Overview'),
    url(r'^CRM-OrderManagement-Overview',views.crm_ordermanagement_overview, name='CRM-OrderManagement-Overview'),

    url(r'^calendar-index',views.calendar_index, name='calendar-index'),
    url(r'^inventory-index',views.inventory_index, name='inventory-index'),
    url(r'^hr-index',views.hr_index, name='hr-index')
]

ERP/clinic/models.py
from django.db import models

class Brand(models.Model):
    brand_id = models.AutoField(primary_key=True)
    brand_name = models.CharField(max_length=32,null=True)
    brand_address = models.CharField(max_length=300,null=True)
    brand_phone_number = models.CharField(max_length=11,null=True)
    brand_manager_id  = models.IntegerField(null=True)

class User(models.Model):
    brand_id = models.IntegerField(null=True)
    user_id = models.AutoField(primary_key=True)
    user_login_id = models.CharField(max_length=8,null=True)
    user_password = models.CharField(max_length=32,null=True)
    user_role = models.CharField(max_length=100,null=True)
    user_name = models.CharField(max_length=300,null=True)
    user_dob = models.CharField(max_length=10,null=True)
    user_phone_number = models.CharField(max_length=11,null=True)
    user_address = models.TextField(null=True)
    user_specialize = models.CharField(max_length=200,null=True)
    user_delete_flag = models.CharField(max_length=1,null=True)

class Customer(models.Model):
    brand_id = models.IntegerField(null=True)
    customer_id = models.AutoField(primary_key=True)
    customer_name = models.CharField(max_length=32,null=True)
    customer_sex = models.CharField(max_length=32,null=True)
    customer_dob = models.CharField(max_length=10,null=True)
    customer_job = models.CharField(max_length=500,null=True)
    customer_company = models.CharField(max_length=500,null=True)
    customer_phone_number = models.CharField(max_length=11,null=True)
    customer_email = models.CharField(max_length=200,null=True)
    customer_address = models.TextField(null=True)
    customer_source = models.CharField(max_length=500,null=True)
    customer_fingerprint = models.TextField(max_length=500,null=True)

#   medical_biography = models.TextField(max_length=500,null=True)#sẽ bỏ cái này
#   def __str__(self):
#    return self.customer_name
# class MedicalHistory(models.Model):
#   # medicalhis_id = models.CharField(max_length=8,null=True)
#   brand_id = models.CharField(max_length=8,null=True)
#   customer_id = models.CharField(max_length=8,null=True)
#   medicalhis_type = models.CharField(max_length=2,null=True)
#   medicalhis_name = models.CharField(max_length=500,null=True)
#   medicalhis_status = models.CharField(max_length=500,null=True)
#   medicalhis_detail = models.CharField(max_length=500,null=True)
#   create_date = models.CharField(max_length=10,null=True)
#   create_by = models.CharField(max_length=10,null=True)
#   update_date = models.CharField(max_length=10,null=True)
#   update_by = models.CharField(max_length=10,null=True)
#   delete_flag = models.CharField(max_length=1,null=True)

# class Relationship(models.Model):
#   customer_id1 = models.CharField(max_length=8,null=True)
#   customer_id2 = models.CharField(max_length=8,null=True)
#   relationship = models.CharField(max_length=32,null=True)
# class CalendarDentist(models.Model):
#   brand_id =  models.CharField(max_length=8,null=True)
#   user_id = models.CharField(max_length=8,null=True)
#   time = models.DateTimeField(null=True)

class Appointment(models.Model):
    brand_id = models.IntegerField(null=True)
    user_id =  models.IntegerField(null=True)
    customer_id =  models.IntegerField(null=True)
    treatment_id = models.IntegerField(null=True)
    appointment_id = models.AutoField(primary_key=True)
    appointment_date = models.CharField(max_length=10,null=True)
    appointment_time = models.CharField(max_length=5,null=True)
    # appointment_name = models.CharField(max_length=500,null=True)
    appointment_content = models.CharField(max_length=500,null=True)
    appointment_assign_id = models.IntegerField(null=True)
    appointment_estimated_time = models.CharField(max_length=8,null=True)
    appointment_estimated_difficulty = models.CharField(max_length=2,null=True)
    appointment_status = models.CharField(max_length=10,null=True)
    appointment_note = models.TextField(null=True)
    appointment_create_date = models.CharField(max_length=10,null=True)
    appointment_create_by = models.CharField(max_length=8,null=True)
    appointment_update_date = models.CharField(max_length=10,null=True)
    appointment_update_by = models.CharField(max_length=8,null=True)
    appointment_delete_flag = models.CharField(max_length=1,null=True)
#   def __str__(self):
#    return self.userID
class Treatment(models.Model):
    brand_id = models.IntegerField(null=True)
    user_id = models.IntegerField(null=True)
    customer_id = models.IntegerField(null=True)
    treatment_id = models.AutoField(primary_key=True)
    treatment_name = models.CharField(max_length=8,null=True)
    treatment_content = models.CharField(max_length=500,null=True)
    treatment_total_payment =  models.IntegerField(null=True)
    treatment_payment_status = models.IntegerField(null=True)
    treatment_status = models.CharField(max_length=10,null=True)
    treatment_create_date = models.CharField(max_length=10,null=True)
    treatment_create_by = models.CharField(max_length=8,null=True)
    treatment_update_date = models.CharField(max_length=10,null=True)
    treatment_update_by = models.CharField(max_length=8,null=True)
    treatment_delete_flag = models.CharField(max_length=1,null=True)

# class TreatmentDetail(models.Model):
#   treatment_id = models.CharField(max_length=8,null=True)
#   treatment_detail_id = models.CharField(max_length=8,null=True)
#   time = models.DateTimeField(null=True)
#   content = models.TextField(max_length=500,null=True)
#   price  = models.IntegerField(null=True)

# class Invoice(models.Model):
#   brand_id = models.CharField(max_length=8,null=True)
#   user_id = models.CharField(max_length=8,null=True)
#   customer_id = models.CharField(max_length=8,null=True)
#   treatment_id = models.CharField(max_length=8,null=True)
#   invoice_id = models.CharField(max_length=8,null=True)
#   pay = models.IntegerField(null=True)

# class Inventory(models.Model):
#   brand_id = models.CharField(max_length=8,null=True)
#   item_id = models.CharField(max_length=8,null=True)
#   item_name = models.IntegerField(null=True)
#   unit = models.CharField(max_length=32,null=True)
#   quantity = models.IntegerField(null=True)

# class Labo(models.Model):
#   brand_id = models.CharField(max_length=8,null=True)
#   labo_name = models.CharField(max_length=100,null=True)
#   address =  models.TextField(max_length=500,null=True)
#   phone_number =  models.CharField(max_length=11,null=True)

# class TreatmentDetailLabo   (models.Model):
#   labo_id = models.CharField(max_length=8,null=True)
#   treatment_id = models.CharField(max_length=8,null=True)
#   send_day = models.DateTimeField(null=True)
#   received_day = models.DateTimeField(null=True)
#   price = models.IntegerField(null=True)

ERP/clinic/views/crm_views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from clinic.models import User
from django.contrib import messages
from django.db import connection

from collections import namedtuple

from .static_variable import KEY
import logging
import datetime

LOGGER = logging.getLogger("ERP")
CURRENT_DATE = datetime.date.today().strftime('%d-%m-%Y')


def crm_dentalclinic_overview(request):
    if request.session.has_key('user_name'):

        # lstCusToday = CalendarAppointment.object.filter(dateAppointment=datetime.date.today())


        sql  =      "   SELECT"
        sql +=      "     appointment_id"
        sql +=      "   , clinic_customer.customer_id"
        sql +=      "   , customer_name"
        sql +=      "   , customer_phone_number"
        sql +=      "   , appointment_time"
        sql +=      "   , appointment_name"
        sql +=      "   , appointment_content"
        sql +=      "   , appointment_status"
        sql +=      "   FROM"
        sql +=      "         clinic_customer"
        sql +=      "   INNER JOIN"
        sql +=      "         clinic_appointment"
        sql +=      "   ON"
        sql +=      "       clinic_customer.customer_id = clinic_appointment.customer_id"
        sql +=      "   WHERE"
        sql +=      "           appointment_date = '{}'".format(CURRENT_DATE)
        if request.session['role'] == '1':
            sql +=  "       AND appointment_assign_id = '{}'".format(request.session['user_id'])
        sql +=      "       AND appointment_delete_flag = '0'"
        sql +=      "   ORDER BY"
        sql +=      "         appointment_status"
        sql +=      "       , appointment_time"
        with connection.cursor() as cursor:
            cursor.execute(sql)
            lstCusToday = namedtuplefetchall(cursor)

        selected_customer = lstCusToday[0]





        context = {
              'user_name' : request.session['user_name']
            , 'lstCusToday' : lstCusToday
            , 'appointment_status' : KEY
        }

        return render(request,"clinic/crm_dentalclinic_overview.html", context)
    else:
        return HttpResponseRedirect('/login/')
    # return render(request,"clinic/crm_dentalclinic_overview.html")

def crm_contactcenter_overview(request):
    return render(request,"clinic/crm_contactcenter_overview.html")

def crm_openchannel_overview(request):
    return render(request,"clinic/crm_openchannel_overview.html")

def crm_ordermanagement_overview(request):
    return render(request,"clinic/crm_ordermanagement_overview.html")


# internal function
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

ERP/clinic/views/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from clinic.models import User
from django.contrib import messages


def login(request):
    try:
        if request.method == 'POST':
            response = HttpResponse()
            username = request.POST['username']
            password = request.POST['password']
            try:
                userlogin  = User.objects.get(user_login_id=username)
                if userlogin.user_password != password:
                    messages.error(request, 'Mật khẩu không đúng! Xin vui lòng nhập lại.')
                    return render(request, 'login.html')
                else:
                    request.session['user_id'] = userlogin.user_id
                    request.session['user_name'] = userlogin.user_name
                    request.session['role'] = userlogin.user_role
                    request.session['brand_id'] = userlogin.brand_id
                    return HttpResponseRedirect("/CRM-DentalClinic-Overview")
            except Exception as e:
                print(e)
                messages.error(request, 'Có phát sinh lỗi hệ thống hoặc tài khoản này không tồn tại!')
                return render(request, 'login.html')
        # elif request.session.has_key('user_id') and request.session.has_key('user_name') and request.session['role']:
        #     return HttpResponseRedirect(request,"index")
        return render(request, 'login.html')
    except Exception as e:
        print(e)
        messages.error(request, 'Có phát sinh lỗi hệ thống hoặc tài khoản này không tồn tại!')
        return render(request, 'login.html')


def logout(request):
    try:
       del request.session['user_id']
       del request.session['user_name']
       del request.session['role']
    except:
       pass
    return HttpResponseRedirect("/login")







def calendar_index(request):
    return render(request,"clinic/calendar_index.html")

def inventory_index(request):
    return render(request,"clinic/inventory_index.html")

def hr_index(request):
    return render(request,"clinic/hr_index.html")

ERP/templates/clinic/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

    <title>Green-Clinic</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, height=device-height">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous"> -->
    <!-- <script src="{% static 'js/style.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script> -->

</head>
<body>
    <!--- Main menu -->
    {% block main-body %}
    {% endblock%}
    <!--- Main body end -->
</body>
</html>

ERP/templates/clinic/calendar.html
{% extends 'clinic/base.html' %}


{%block main-body%}
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light bg-white" >
                <a class="navbar-brand" href="#">LOGO</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbars-menu"    aria-controls="navbars-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'clinic:crm-overview' %}">Messenger CRM <sup>TM</sup></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'clinic:calendar-index' %}">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clinic:inventory-index' %}">Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clinic:hr-index' %}">HR</a>
                        </li>
                    </ul>
                    <ul class="navbar-text">
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-commenting" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-bell-o" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--- Main menu end -->

    <!--- Menu Second start -->
    <div class="container-fluid" id="menu-second">
        <div class="container">
            {% block second-menu%}

            {% endblock %}
        </div>
    </div>
    <!--- Menu Second end -->

    <!--- Main body -->
    <div class="container-fluid" id="main-body">
        <div class="row">
            {% block body %}
                
            {% endblock %}
        </div>
    </div>
{%endblock%}

ERP/templates/clinic/calendar_index.html
{% extends 'clinic/calendar.html' %}

{% block second-menu%}
    <ul class="nav nav-tabs">
        Comming soon
    </ul>
{% endblock %}

{% block body %}
    Comming soon  
{% endblock %}

ERP/templates/clinic/crm.html
{% extends 'clinic/base.html' %}


{%block main-body%}
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light bg-white" >
                <a class="navbar-brand" href="#">LOGO</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbars-menu" aria-controls="navbars-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'clinic:CRM-DentalClinic-Overview' %}">Messenger CRM <sup>TM</sup></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clinic:calendar-index' %}">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clinic:inventory-index' %}">Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clinic:hr-index' %}">HR</a>
                        </li>
                    </ul>
                    <ul class="navbar-text">
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-commenting" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-bell-o" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item" >
                            <a href="" style="font-size: 30px !important; color: tomato">
                                <i class="fa fa-user-circle" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--- Main menu end -->

    <!--- Second menu and main body start -->
    <div>
        {% block second-menu%}

        {% endblock %}
    </div>
    <!--- Second menu and main body end -->


{%endblock%}

ERP/templates/clinic/crm_contactcenter.html
{% extends 'clinic/crm.html' %}

{% block second-menu%}
    <div class="container-fluid" id="menu-second">
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-DentalClinic-Overview' %}">Dental Clinic</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-OpenChannel-Overview' %}">Open channel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'clinic:CRM-ContactCenter-Overview' %}">Contact center</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-OrderManagement-Overview' %}">Order management</a>
                </li>
            </ul>
        </div>
    </div>


    <!--- Main body -->
    <div class="container-fluid" id="main-body">
        <div>
            {% block body %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

ERP/templates/clinic/crm_contactcenter_overview.html
{% extends 'clinic/crm_contactcenter.html' %}


{% block body %}
<div class="row">
    Comming soon
</div>    
{% endblock %}

ERP/templates/clinic/crm_dentalclinic.html
{% extends 'clinic/crm.html' %}

{% block second-menu%}
    <div class="container-fluid" id="menu-second">
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'clinic:CRM-DentalClinic-Overview' %}">Dental Clinic</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-OpenChannel-Overview' %}">Open channel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-ContactCenter-Overview' %}">Contact center</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-OrderManagement-Overview' %}">Order management</a>
                </li>
            </ul>
        </div>
    </div>


    <!--- Main body -->
    <div class="container-fluid" id="main-body">
        {% block body %}

        {% endblock %}
    </div>
{% endblock %}

ERP/templates/clinic/crm_openchannel.html
{% extends 'clinic/crm.html' %}

{% block second-menu%}
    <div class="container-fluid" id="menu-second">
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-DentalClinic-Overview' %}">Dental Clinic</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'clinic:CRM-OpenChannel-Overview' %}">Open channel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-ContactCenter-Overview' %}">Contact center</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-OrderManagement-Overview' %}">Order management</a>
                </li>
            </ul>
        </div>
    </div>


    <!--- Main body -->
    <div class="container-fluid" id="main-body">
        <div class="row">
            {% block body %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

ERP/templates/clinic/crm_openchannel_overview.html
{% extends 'clinic/crm_openchannel.html' %}


{% block body %}
<div class="row">
    Comming soon
</div>    
{% endblock %}

ERP/templates/clinic/crm_ordermanagement.html
{% extends 'clinic/crm.html' %}

{% block second-menu%}
    <div class="container-fluid" id="menu-second">
        <div class="container">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-DentalClinic-Overview' %}">Dental Clinic</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-OpenChannel-Overview' %}">Open channel</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'clinic:CRM-ContactCenter-Overview' %}">Contact center</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'clinic:CRM-OrderManagement-Overview' %}">Order management</a>
                </li>
            </ul>
        </div>
    </div>


    <!--- Main body -->
    <div class="container-fluid" id="main-body">
        <div class="row">
            {% block body %}

            {% endblock %}
        </div>
    </div>
{% endblock %}

ERP/templates/clinic/hr.html
{% extends 'clinic/base.html' %}


{%block main-body%}
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light bg-white" >
                <a class="navbar-brand" href="#">LOGO</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbars-menu"    aria-controls="navbars-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'clinic:crm-overview' %}">Messenger CRM <sup>TM</sup></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'clinic:calendar-index' %}">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'clinic:inventory-index' %}">Inventory</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'clinic:hr-index' %}">HR</a>
                        </li>
                    </ul>
                    <ul class="navbar-text">
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-commenting" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-bell-o" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--- Main menu end -->

    <!--- Menu Second start -->
    <div class="container-fluid" id="menu-second">
        <div class="container">
            {% block second-menu%}

            {% endblock %}
        </div>
    </div>
    <!--- Menu Second end -->

    <!--- Main body -->
    <div class="container-fluid" id="main-body">
        <div class="row">
            {% block body %}
                
            {% endblock %}
        </div>
    </div>
{%endblock%}

ERP/templates/clinic/inventory.html
{% extends 'clinic/base.html' %}


{%block main-body%}
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light bg-white" >
                <a class="navbar-brand" href="#">LOGO</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbars-menu"    aria-controls="navbars-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-menu">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'clinic:crm-overview' %}">Messenger CRM <sup>TM</sup></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'clinic:calendar-index' %}">Calendar</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'clinic:inventory-index' %}">Inventory</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'clinic:hr-index' %}">HR</a>
                        </li>
                    </ul>
                    <ul class="navbar-text">
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-commenting" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-bell-o" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="text-primary">
                                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--- Main menu end -->

    <!--- Menu Second start -->
    <div class="container-fluid" id="menu-second">
        <div class="container">
            {% block second-menu%}

            {% endblock %}
        </div>
    </div>
    <!--- Menu Second end -->

    <!--- Main body -->
    <div class="container-fluid" id="main-body">
        <div class="row">
            {% block body %}
                
            {% endblock %}
        </div>
    </div>
{%endblock%}

ERP/templates/clinic/inventory_index.html
{% extends 'clinic/inventory.html' %}

{% block second-menu%}
    <ul class="nav nav-tabs">
        Comming soon
    </ul>
{% endblock %}

{% block body %}
    Comming soon  
{% endblock %}