ERP/ERP/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('clinic.urls')),
]

ERP/clinic/urls.py
from django.conf.urls import url

from . import views

app_name = "clinic"

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),

    url(r'^CRM-DentalClinic-Overview',views.crm_dentalclinic_overview, name='CRM-DentalClinic-Overview'),
    url(r'^CRM-ContactCenter-Overview',views.crm_contactcenter_overview, name='CRM-ContactCenter-Overview'),
    url(r'^CRM-OpenChannel-Overview',views.crm_openchannel_overview, name='CRM-OpenChannel-Overview'),
    url(r'^CRM-OrderManagement-Overview',views.crm_ordermanagement_overview, name='CRM-OrderManagement-Overview'),

    url(r'^calendar-index',views.calendar_index, name='calendar-index'),
    url(r'^inventory-index',views.inventory_index, name='inventory-index'),
    url(r'^hr-index',views.hr_index, name='hr-index')
]

ERP/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Auth Demo</title>
        <!-- Core CSS - Include with every page -->
        
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/me.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'css/schedule.css' %}" rel="stylesheet">

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        
        <script src="{% static 'js/style.js' %}"></script>

    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Logo</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li> <!--  Header menu -->
                            {% block menu %}
                            {% endblock %}
                            
                        </li>
                        <li class="find"> <!--  Header search -->
                            <div class="span12">
                                <form id="searchForm" method="post">
                                    <div class="input-append span12">
                                        <input type="text" class="search-query" placeholder="Số điện thoại, booking">
                                        <span class="icon-bar"><i class="fa fa-search" aria-hidden="true"></i></span>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <li class="dropdown"> <!--  Header User-Infor -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="/home">home</a>
                                </li>
                                <li>
                                    <a href="#">Another action</a>
                                </li>
                                <li>
                                    <a href="#">Something else here</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">Separated link</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="/logout">Logout</a>
                                </li>
                            </ul>
                        </li>
                        

                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    

    </body>
</html>

ERP/templates/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Projection Semantic Roles</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <script src="{% static 'js/jquery.min.js' %}"></script>
    </head>
    <body>
        <div style="text-align: center;">
            <div class="card" style="width: 500px; position: relative; margin-left: auto; margin-right: auto; margin-top: 150px; border-color: #007BFF; color: #FFFFFF">
                <div class="card-header bg-primary">Vui lòng đăng ký hoặc đăng nhập</div>
                <div class="card-body">
                    <form method="POST" action="{% url 'clinic:login' %}">
                        {% csrf_token %}
                        {% if messages %}
                            {% for message in messages %}
                                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                                    <div id="message" class="alert alert-danger alert-dismissable">
                                {% else %}
                                    <div id="message" class="alert alert-info alert-dismissable">
                                {% endif %}
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="input-group" style="width: 300px; margin-left: auto; margin-right: auto;">
                            <span class="input-span input-group-addon"><i class=" fa fa-fw fa-user"></i></span>
                            <input id="email" type="text" class="form-control" name="username" placeholder="Email">
                        </div>
                        <div class="input-group" style="width: 300px; position: relative; margin-left: auto; margin-right: auto; margin-top: 10px;">
                            <span class="input-span input-group-addon"><i class="fa fa-fw fa-key"></i></span>
                            <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                        <input class="btn btn-primary" style="margin-top: 15px;" type="submit" name="signin" value="Đăng nhập" />
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>